Implement ssh for Bodega provider
Summary:
In order to run roachtest, we need the ability to ssh into nodes and
run commmands on them. Previously, `roachprod` only supports
gcloud and aws as resource provider, and its ssh-related methods
can only ssh into gcloud and aws machines.

In this diff, we made roachprod's `ssh`, `run`, `put`, `get` commands
compatible with Bodega provider. Currently, nodes are `ubuntu_machine`
requested from Bodega, so this diff might only work with
`ubuntu_machine`.

Test Plan:
`./build.sh` builds successfully.
Tested functionality on both Bodega and local cluster

Test on Bodega clusters:
1.SSHed into node 1 of ubuntu-cluster1 with
`roachprod ssh ubuntu-cluster1:1`
2.Connect to a non-exist cluster failed as expected.
```
$ roachprod ssh ubuntu-cluster3:1
Error:  unknown cluster: ubuntu-cluster3

Available clusters:
  ubuntu-cluster1
  ubuntu-cluster2

Hint: use "roachprod sync" to update the list of available clusters.
```
3.Ran `date` command on each node of the cluster successfully.
```
$ roachprod run ubuntu-cluster1 -- date
ubuntu-cluster1: date 4/4
   1: Fri Apr 20 11:25:58 PDT 2018
   2: Fri Apr 20 11:25:58 PDT 2018
   3: Fri Apr 20 11:25:58 PDT 2018
   4: Fri Apr 20 11:25:58 PDT 2018
```
4.Ran command on node 2 of ubuntu-cluster1
```
$ roachprod run ubuntu-cluster1:2 -- date
Fri Apr 20 12:29:06 PDT 2018
```
5.Successfully ran put command to put files on all nodes:
```
$ roachprod put ubuntu-cluster1 file.txt /home/ubuntu/file.txt
ubuntu-cluster1: putting file.txt /home/ubuntu/file.txt
   1: done
   2: done
   3: done
   4: done
$ roachprod run ubuntu-cluster1 "less /home/ubuntu/file.txt"
ubuntu-cluster1: less /home/ubuntu/file.txt 4/4
   1: Hello!
   2: Hello!
   3: Hello!
   4: Hello!
```
6.Successfully ran get command to get files from one node:
```
$ roachprod get ubuntu-cluster1:1 file.txt
ubuntu-cluster1: getting file.txt file.txt
   1: done
$ more file.txt
Hello!
```

Test on local cluster:
1.SSHed into node 1 of local cluster with
`roachprod ssh local:1`
2.Ran `date` command on each node of local cluster.
3.Ran command on node 1 of local cluster
4.Successfully put files on local nodes:
`roachprod put local file.txt file.txt`
5.Successfully get files from local nodes:
`roachprod get local:1 file.txt`

Reviewers: #shield, ND, hao

Reviewed By: #shield, ND, hao

Subscribers: hao, arijit

Tags: #cly

JIRA Issues: CDM-88890

Differential Revision: https://phabricator.rubrik.com/D45111